package vista;

/**
 * @author catas
 */

public class ActualizarProveedorForm extends javax.swing.JFrame {

  /**
   * Creates new form ActualizarProveedorForm
   */
  public ActualizarProveedorForm() {
    initComponents();
  }

  
  public boolean actualizarProveedorDatosCorrectos(){
    return validarNombre(txtNombreBuscar.getText());
  }
  
  
  public boolean validarNombre(String pNombre){
    if(pNombre != null && !pNombre.equals("")){
      return true;  
    }  
    else{
      return false;  
    }
  }
  
  
  public boolean nombreNuevoDatosCorrectos(){
    return validarNombreNuevo(txtNuevoNombre.getText());
  }
  
  
  public boolean validarNombreNuevo(String pNombreNuevo){
    return pNombreNuevo != null && !pNombreNuevo.equals("");
  }
  
  
  public boolean telefonoNuevoDatosCorrectos(){
    return validarTelefonoNuevo(Integer.parseInt((txtNuevoTelefono.getText())));
  }
  
  
  public boolean validarTelefonoNuevo(int pTelefonoNuevo){
    return pTelefonoNuevo != 0;
  }
  
  
  public boolean correoNuevoDatosCorrectos(){
    return validarCorreoNuevo(txtNuevoCorreo.getText());
  }
  
  
  public boolean validarCorreoNuevo(String pCorreoNuevo){
    if(pCorreoNuevo != null && !pCorreoNuevo.equals("")){
      return true;  
    }  
    else{
      return false;  
    }
  }
  
  
  public boolean sitioNuevoDatosCorrectos(){
    return validarSitioNuevo(txtNuevoSitio.getText());
  }
  
  
  public boolean validarSitioNuevo(String pCorreoNuevo){
    if(pCorreoNuevo != null && !pCorreoNuevo.equals("")){
      return true;  
    }  
    else{
      return false;  
    }
  }
  
  
  public boolean redesNuevoDatosCorrectos(){
    return validarRedesNuevo(txtNuevasRedes.getText());
  }
  
  
  public boolean validarRedesNuevo(String pRedesNuevo){
    if(pRedesNuevo != null && !pRedesNuevo.equals("")){
      return true;  
    }  
    else{
      return false;  
    }
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextField2 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    txtNombreBuscar = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaProveedores = new javax.swing.JTable();
    txtNuevoNombre = new javax.swing.JTextField();
    btnActualizarNombre = new javax.swing.JButton();
    txtNuevoTelefono = new javax.swing.JTextField();
    btnActualizarTelefono = new javax.swing.JButton();
    txtNuevoCorreo = new javax.swing.JTextField();
    btnActualizarCorreo = new javax.swing.JButton();
    txtNuevoSitio = new javax.swing.JTextField();
    btnActualizarWeb = new javax.swing.JButton();
    txtNuevasRedes = new javax.swing.JTextField();
    btnActualizarRedes = new javax.swing.JButton();
    btnVolver = new javax.swing.JButton();
    btnCargarDatos = new javax.swing.JButton();

    jTextField2.setText("jTextField2");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("Actualizar datos de proveedor");

    jLabel2.setText("Nuevo nombre:");

    jLabel3.setText("Teléfono:");

    jLabel4.setText("Correo electrónico:");

    jLabel5.setText("Sitio web:");

    jLabel6.setText("Redes sociales:");

    jLabel7.setText("Por favor, ingrese el nombre del proveedor al cual le quiere modificar su información:");

    btnBuscar.setText("Buscar");

    jLabel8.setText("Datos encontrados:");

    tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String [] {
        "Cédula", "Correo electrónico", "Nombre", "Teléfono", "Sitio web", "Redes sociales"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        true, true, false, true, true, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tablaProveedores);

    btnActualizarNombre.setText("Actualizar nombre");

    txtNuevoTelefono.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNuevoTelefonoActionPerformed(evt);
      }
    });

    btnActualizarTelefono.setText("Actualizar teléfono");

    btnActualizarCorreo.setText("Actualizar correo");

    btnActualizarWeb.setText("Actualizar sitio");

    btnActualizarRedes.setText("Actualizar redes");

    btnVolver.setText("Volver");

    btnCargarDatos.setText("Cargar datos");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(55, 55, 55))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel3)
                      .addComponent(jLabel4)
                      .addComponent(jLabel5)
                      .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(txtNuevoNombre)
                  .addComponent(txtNuevoCorreo)
                  .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                  .addComponent(txtNuevasRedes)))
              .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(txtNuevoSitio)))
            .addGap(56, 56, 56)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(btnActualizarCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnActualizarNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnActualizarTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnActualizarWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnActualizarRedes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(91, 91, 91)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(119, 119, 119)
        .addComponent(btnVolver)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCargarDatos)
        .addGap(208, 208, 208))
      .addGroup(layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel8)
          .addComponent(jLabel7))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(120, 120, 120)
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(btnBuscar)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(jLabel1)
        .addGap(21, 21, 21)
        .addComponent(jLabel7)
        .addGap(13, 13, 13)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar))
        .addGap(18, 18, 18)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarNombre))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarTelefono))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(txtNuevoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarCorreo))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(txtNuevoSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarWeb))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(txtNuevasRedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarRedes))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnVolver)
          .addComponent(btnCargarDatos))
        .addGap(34, 34, 34))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtNuevoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoTelefonoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNuevoTelefonoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ActualizarProveedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ActualizarProveedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ActualizarProveedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ActualizarProveedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ActualizarProveedorForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnActualizarCorreo;
  public javax.swing.JButton btnActualizarNombre;
  public javax.swing.JButton btnActualizarRedes;
  public javax.swing.JButton btnActualizarTelefono;
  public javax.swing.JButton btnActualizarWeb;
  public javax.swing.JButton btnBuscar;
  public javax.swing.JButton btnCargarDatos;
  public javax.swing.JButton btnVolver;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel2;
  public javax.swing.JLabel jLabel3;
  public javax.swing.JLabel jLabel4;
  public javax.swing.JLabel jLabel5;
  public javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  public javax.swing.JLabel jLabel8;
  public javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField2;
  public javax.swing.JTable tablaProveedores;
  public javax.swing.JTextField txtNombreBuscar;
  public javax.swing.JTextField txtNuevasRedes;
  public javax.swing.JTextField txtNuevoCorreo;
  public javax.swing.JTextField txtNuevoNombre;
  public javax.swing.JTextField txtNuevoSitio;
  public javax.swing.JTextField txtNuevoTelefono;
  // End of variables declaration//GEN-END:variables
}
