package vista;

/**
 * @author catas
 */

public class ActualizarCategoriaForm extends javax.swing.JFrame {

  /**
   * Creates new form ActualizarProveedorForm
   */
  public ActualizarCategoriaForm() {
    initComponents();
  }

  
  public boolean actualizarProveedorDatosCorrectos(){
    return validarNombre(txtNombreBuscar.getText());
  }
  
  
  public boolean validarNombre(String pNombre){
    if(pNombre != null && !pNombre.equals("")){
      return true;  
    }  
    else{
      return false;  
    }
  }
  
  
  public boolean nombreNuevoDatosCorrectos(){
    return validarNombreNuevo(txtNuevoNombre.getText());
  }
  
  
  public boolean validarNombreNuevo(String pNombreNuevo){
    return pNombreNuevo != null && !pNombreNuevo.equals("");
  }
  
  
  public boolean descripcionNuevaDatosCorrectos(){
    return validarDescripcionNueva(txtDescripcionNueva.getText());
  }
  
  
  public boolean validarDescripcionNueva(String pDescripcionNueva){
    return pDescripcionNueva != null && !pDescripcionNueva.equals("");
  }
  
  
  
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextField2 = new javax.swing.JTextField();
    jToggleButton1 = new javax.swing.JToggleButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    txtNombreBuscar = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaCategorias = new javax.swing.JTable();
    txtNuevoNombre = new javax.swing.JTextField();
    btnActualizarNombre = new javax.swing.JButton();
    btnActualizarDescripcion = new javax.swing.JButton();
    btnVolver = new javax.swing.JButton();
    btnCargarDatos = new javax.swing.JButton();
    btnCambiarEstado = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtDescripcionNueva = new javax.swing.JTextArea();

    jTextField2.setText("jTextField2");

    jToggleButton1.setText("jToggleButton1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("Actualizar datos de la categoría");

    jLabel2.setText("Nuevo nombre:");

    jLabel3.setText("Descripción:");

    jLabel7.setText("Por favor, ingrese el nombre de la categoría a la cual le quiere modificar su información:");

    btnBuscar.setText("Buscar");

    jLabel8.setText("Datos encontrados:");

    tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Código", "Nombre", "Descripción", "Estado"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        true, true, false, true
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tablaCategorias);

    btnActualizarNombre.setText("Actualizar nombre");

    btnActualizarDescripcion.setText("Actualizar descripción");

    btnVolver.setText("Volver");

    btnCargarDatos.setText("Cargar datos");

    btnCambiarEstado.setText("Cambiar estado de categoría");

    txtDescripcionNueva.setColumns(20);
    txtDescripcionNueva.setRows(5);
    jScrollPane2.setViewportView(txtDescripcionNueva);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtNuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
              .addComponent(jScrollPane2))
            .addGap(56, 56, 56)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(btnActualizarNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnActualizarDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(91, 91, 91)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(119, 119, 119)
        .addComponent(btnVolver)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCargarDatos)
        .addGap(208, 208, 208))
      .addGroup(layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel8)
          .addComponent(jLabel7))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(120, 120, 120)
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(btnBuscar))
          .addGroup(layout.createSequentialGroup()
            .addGap(210, 210, 210)
            .addComponent(btnCambiarEstado)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(jLabel1)
        .addGap(21, 21, 21)
        .addComponent(jLabel7)
        .addGap(13, 13, 13)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar))
        .addGap(18, 18, 18)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnActualizarNombre))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnActualizarDescripcion)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
            .addComponent(btnCambiarEstado)
            .addGap(58, 58, 58)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnVolver)
              .addComponent(btnCargarDatos))
            .addGap(34, 34, 34))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ActualizarCategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ActualizarCategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ActualizarCategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ActualizarCategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ActualizarCategoriaForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnActualizarDescripcion;
  public javax.swing.JButton btnActualizarNombre;
  public javax.swing.JButton btnBuscar;
  public javax.swing.JButton btnCambiarEstado;
  public javax.swing.JButton btnCargarDatos;
  public javax.swing.JButton btnVolver;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel2;
  public javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel7;
  public javax.swing.JLabel jLabel8;
  public javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JToggleButton jToggleButton1;
  public javax.swing.JTable tablaCategorias;
  public javax.swing.JTextArea txtDescripcionNueva;
  public javax.swing.JTextField txtNombreBuscar;
  public javax.swing.JTextField txtNuevoNombre;
  // End of variables declaration//GEN-END:variables
}
